version: "3.9"
services:
  app:
    container_name: payment-api
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - payment_api_net
  db:
    image: mysql:8.0
    container_name: payment-api-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8083:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
    - payment_api_net
  nginx:
    image: nginx:alpine
    container_name: payment-api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - payment_api_net
networks:
  payment_api_net:
    driver: bridge